--insert문
--INSERT(컬럼명, 컬럼명 갯수와 VALUSE개수가 맞아야된다.)
--컬럼명 타입과 VALUSE 타입이 같아야된다.
--NOT NULL, PRIMARY KEY 제약조건을 체크할듯
CREATE TABLE DEPT(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13) NOT NULL
);

--칼럼 DEPTNO에 10번 부서, DNAME에는 ‘ACCOUNTING’을, LOC에는 ‘NEW YORK’을 추가하자
 INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES(10,'ACCOUTUING','NEW YORK');
  INSERT INTO DEPT VALUES(11,'ACCOUTUING1','NEW YORK1');
    INSERT INTO DEPT VALUES(13,NULL,'NEW YORK3'); -- 제일 좋은 방법!!
 INSERT INTO DEPT(DNAME, LOC) VALUES('ACCOUTUING2','NEW YORK1');
 
 SELECT * FROM DEPT;

DROP TABLE DEPT;

SELECT * FROM TAB WHERE TNAME = 'DEPT';

ALTER table dept
    MODIFY(deptno number(4), dname VARCHAR2(30) not null);

UPDATE dept set dname ='임시값' WHERE dname  is null;


CREATE TABLE TB_CUSTOMER(
    CUSTOMER_CD   VARCHAR2(10) PRIMARY KEY, 
    CUSTOMER_NM   VARCHAR2(20) not null,            
    MW_FLG        VARCHAR2(2) not null,        
    BIRTH_DAY     DATE,           
    PHONE_NUMBER  VARCHAR2(20) not null,         
    EMAIL         VARCHAR2(50) not null,            
    TOTAL_POINT   NUMBER(10) not null,       
    REG_DTTM      TIMESTAMP(0)
);

INSERT INTO TB_CUSTOMER (
    CUSTOMER_CD, CUSTOMER_NM, MW_FLG, BIRTH_DAY, PHONE_NUMBER, EMAIL, TOTAL_POINT, REG_DTTM
) VALUES (
    '2017042', '강원진', 'M', DATE '1981-06-03', '010-8202-8790', 'wjgang@navi.com', 280300,TIMESTAMP '2017-01-23 13:24:32'
);
INSERT INTO TB_CUSTOMER (
    CUSTOMER_CD, CUSTOMER_NM, MW_FLG, BIRTH_DAY, PHONE_NUMBER, EMAIL, TOTAL_POINT, REG_DTTM
) VALUES (
   '2017053', '나경숙', 'W', DATE '1989-12-25', '010-4509-0043', 'ksna#boram.co.kr', 4500, TIMESTAMP '2017-02-10 18:09:30'
);
INSERT INTO TB_CUSTOMER (
    CUSTOMER_CD, CUSTOMER_NM, MW_FLG, BIRTH_DAY, PHONE_NUMBER, EMAIL, TOTAL_POINT, REG_DTTM
) VALUES (
    '2017108', '박승대', 'M',DATE '1971-04-30', ' NULL', 'sdpark@haso.com', 23450 ,TIMESTAMP '2017-05-08 20:34:50'
);



DROP TABLE TB_CUSTOMER;
SELECT * FROM TB_CUSTOMER;